name: intellibox
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  advance_animated_progress_indicator: ^0.0.1
  animate_do: ^3.0.2
  async_button_builder: ^3.0.0+1
  auth_buttons: ^3.0.3
  awesome_dialog: ^3.0.2
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  getwidget: ^4.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.1.0
  http: ^1.2.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  json_annotation: ^4.8.0
  loader_overlay: ^4.0.0
  translator: ^1.0.0
  fluttertoast:
  flutter_markdown: ^0.7.3
  markdown: ^7.2.1
  gif_view: ^0.4.4
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.6.1
  rename: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.3


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

    - .env
