name: intellibox
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  auth_buttons: ^1.0.1+4
  awesome_dialog: ^3.0.2
  build_runner: ^2.3.3
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  getwidget: ^3.1.1
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  http: ^0.13.5
  image_picker: ^0.8.7+3
  json_annotation: ^4.8.0
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true


  assets:
    - assets/images/
