name: intellibox
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  advance_animated_progress_indicator: ^0.0.1
  animate_do: ^3.0.2
  async_button_builder: ^3.0.0+1
  auth_buttons: ^1.0.1+4
  awesome_dialog: ^3.0.2
  build_runner: ^2.3.3
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  getwidget: ^3.1.1
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  http: ^0.13.5
  image_gallery_saver: ^2.0.3
  image_picker: ^0.8.7+4
  json_annotation: ^4.8.0
  loader_overlay: ^2.2.0
  translator: ^0.1.7
  fluttertoast:
  flutter_markdown: ^0.6.18+3
  markdown: ^7.2.1
  gif_view: ^0.3.1
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  rename: ^2.1.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

    - .env
